[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dextop-mode"
version = "1.0.26"
description = "DeXtop Mode: Samsung DeX & Android Desktop Mode on Linux, macOS & Windows"
readme = "README.md"
authors = [
    { name = "Romain Guillon (super-magistro)" }
]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Hardware",
    "Topic :: Utilities"
]
dependencies = [
    "customtkinter>=5.2.0",
    "Pillow",
    "qrcode",
    "zeroconf>=0.13.0"
]
requires-python = ">=3.8"

[project.scripts]
dextop-mode = "dextop:main"
dextop = "dextop:main"

[project.urls]
Homepage = "https://github.com/super-magistro/DeXtop-mode"
Repository = "https://github.com/super-magistro/DeXtop-mode"
"Bug Tracker" = "https://github.com/super-magistro/DeXtop-mode/issues"
